on: [push]

jobs:
  nsec:
    runs-on: ubuntu-latest
    name: BSides Buffalo NY 2023
    steps:
      - run: |
            id
            uname -a
            env
            echo "Hello BSides Buffalo NY 2023!"
