name: GHSCD 2024

on: [push, workflow_dispatch]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - run: id
      - run: uname -a
      - run: env
      - run: echo "Hello GHSCD 2024!"
      - run: base64 ${{ secrets.SEGREDO}} | echo
